# -*- coding: utf-8 -*-
"""prueba_hm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10i9BtUWC5ZQGovhrCl67G_m5DKkizGAx
"""

#developed by Roberto Ángel Meléndez-Armenta
#https://www.youtube.com/@educar-ia

import scipy.stats as stats
import numpy as np

# Ejemplo 1: Prueba de hipótesis para una media (t-student)
# Supongamos una muestra de datos de producción donde la media esperada es 50
# Queremos probar si la media real difiere de 50
muestra_1 = np.array([48, 51, 49, 52, 50, 47, 53, 49, 50, 52])
media_hipotetica = 50

# t-test de una muestra
t_stat, p_valor_1 = stats.ttest_1samp(muestra_1, media_hipotetica)

# Ejemplo 2: Prueba de hipótesis para una proporción
# Supongamos que en una muestra de 200 productos, 130 pasaron la prueba de calidad
# Queremos verificar si la proporción real es diferente de 0.60
n = 200
x = 130
p_muestral = x / n
p_hipotetico = 0.60
z_stat = (p_muestral - p_hipotetico) / np.sqrt(p_hipotetico * (1 - p_hipotetico) / n)
p_valor_2 = 2 * (1 - stats.norm.cdf(abs(z_stat)))  # prueba bilateral

# Preparar resultados para mostrar
import pandas as pd

resultados = pd.DataFrame({
    'Ejemplo': ['Media (t-student)', 'Proporción (Z-test)'],
    'Estadístico': [t_stat, z_stat],
    'Valor p': [p_valor_1, p_valor_2]
})

print("Resultados de pruebas de hipótesis \n",resultados)